service: serverless-telepresence-example
frameworkVersion: "2"

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi: "POST /"

plugins:
  localPath: ".."
  modules:
    - lib
